server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    location /catalog-service/ {
        proxy_pass http://yarpapigateway:8080/catalog-service/;
    }

    location /basket-service/ {
        proxy_pass http://yarpapigateway:8080/basket-service/;
    }

    location /ordering-service/ {
        proxy_pass http://yarpapigateway:8080/ordering-service/;
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
